server:
    port: 8080
spring:
    application:
        name: Riding_Events
    datasource:
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/bikefit?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
            username: root
            password: 1234
    cache:
        redis:
            host: localhost
            jedis:
                pool:
                    min-idle: 5
                    max-idle: 10
                    max-wait: -1
            port: 6379
            timeout: 1000
#            time-to-live: 60000
#    thymeleaf:
#        prefix: classpath:/templates/

mybatis-plus:
    configuration:
        #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            id-type: ASSIGN_ID
